### ISSUE TITLE
project dead?

### ISSUE THREAD

**Issue by gbzret4d** [OverflowCat/AutoArchive#1]
Hi,
just wanted to know if this project is dead/abandoned or if you are still working on it?

regards

**Comment by OverflowCat** [comment]
**Nope.**
Last time I checked, this script still works.
![image](https://user-images.githubusercontent.com/20166026/84570659-7fa47880-adc1-11ea-9253-53b319ae7c75.png)

As I [wrote in the code](https://github.com/OverflowCat/AutoArchive/blob/bbbe5b3b5be5955115a6a22b4dc5e10dffc5d333/autoarchive.js#L52), this repo is a _fork_ from https://greasyfork.org/en/scripts/368062-autosave-to-internet-archive-wayback-machine, which does not have a GitHub repo. I added specific rules to make the original one more useful, such as detecting URL change on Twitter Web App so that every tweet you view, rather than the first page, will be archived, and excluding auth pages so you won't bother when you find your login page expired before you visit it.

I strongly recommend you the extension, [**Save To The Wayback Machine**](https://chrome.google.com/webstore/detail/save-to-the-wayback-machi/eebpioaailbjojmdbmlpomfgijnlcemk). Combined with this script, the tool is useful for checking if the autosave works.
![image](https://user-images.githubusercontent.com/20166026/84570866-95666d80-adc2-11ea-8f48-e2c41a824064.png)
